FROM node:16.15.1-alpine AS builder

WORKDIR /opt/app
COPY . .

RUN corepack enable
RUN pnpm i
RUN pnpm run staging


FROM nginx:1.22.0-alpine

WORKDIR /usr/share/nginx/html
COPY --from=builder /opt/app/dist .
COPY nginx.conf /etc/nginx/conf.d
RUN rm /etc/nginx/conf.d/default.conf
