FROM node:18.16.0-alpine AS builder

WORKDIR /opt/app
COPY .npmrc .nvmrc package.json pnpm-lock.yaml /opt/app/
RUN corepack enable && pnpm i

COPY . .
RUN pnpm run build --mode staging


FROM nginx:1.22.1-alpine

WORKDIR /usr/share/nginx/html
COPY --from=builder /opt/app/dist .
COPY nginx.conf /etc/nginx/conf.d
RUN rm /etc/nginx/conf.d/default.conf
